import { FontUtil } from './font.js'


// const OpenAI14Segment = {
//   'A': 'BCEFG1G2KMN',
//   'B': 'ABCDEFG1G2JKLN',
//   'C': 'ADEF',
//   'D': 'ABCDEFMNFG1G2',
//   'E': 'ABCDEFHG1G2',
//   'F': 'ABCG1G2HEF',
//   'G': 'ABCDEFG1G2N',
//   'H': 'ABCG1G2EFKMN',
//   'I': 'BCHK',
//   'J': 'BCDHKLN',
//   'K': 'AFG1G2CEKMN',
//   'L': 'DEFHG1G2',
//   'M': 'ACEG1G2KHNM',
//   'N': 'ACG1G2EFKMN',
//   'O': 'ABCDEFG1G2',
//   'P': 'ABCG1G2EFJK',
//   'Q': 'ABCDEFG1G2M',
//   'R': 'ABCG1G2EFJKM',
//   'S': 'ABCDFG1G2N',
//   'T': 'AJM',
//   'U': 'BCDEFG1G2N',
//   'V': 'CEG1G2AKM',
//   'W': 'ACEG1G2KHNM',
//   'X': 'BCEFG1G2AKM',
//   'Y': 'BDG1G2AKM',
//   'Z': 'ABDEFG1G2MN'
// }


// {
//   ' ': '',
//   '0': 'ABCDEF',
//   '1': 'BC',
//   '2': 'ABG1ED',
//   '3': 'ABG1CD',
//   '4': 'FG1BC',
//   '5': 'AFG1CD',
//   '6': 'AFEDCG1',
//   '7': 'ABC',
//   '8': 'ABCDEFG1',
//   '9': 'ABCDFG1',
//   'A': 'ABCDEFHKG1G2N',
//   'B': 'CDEFKG1G2',
//   'C': 'ADEFG2',
//   'D': 'BCDEG1G2K',
//   'E': 'ADEFG1G2K',
//   'F': 'AEFG1G2HK',
//   'G': 'ACDEFG2K',
//   'H': 'BCEFG1G2HK',
//   'I': 'BCJ',
//   'J': 'DEFG2',
//   'K': 'EFG1HKMN',
//   'L': 'DEFG2',
//   'M': 'ACEG1IKM',
//   'N': 'ABCEG1HKMNM',
//   'O': 'ABCDEFG1G2',
//   'P': 'ABEFG1G2H',
//   'Q': 'ABCDEFG1G2K',
//   'R': 'ABEFG1KH',
//   'S': 'ACDFG2K',
//   'T': 'AJK',
//   'U': 'BCDEFG2K',
//   'V': '',
//   'W': '',
//   'X': '',
//   'Z': '',
// }



// {
//   '0': 'ABCFEDG2',
//   '1': 'EF',
//   '2': 'ABGEDG1',
//   '3': 'ABGEDG2',
//   '4': 'FBEGDG2',
//   '5': 'AFBGEDG2',
//   '6': 'AFBCEDG2',
//   '7': 'ABE',
//   '8': 'ABCDEFG2',
//   '9': 'ABEGDG2',
//   'A': 'ABCGEDG1G2',
//   'B': 'ABCFEDG1G2',
//   'C': 'AFEDG2',
//   'D': 'BCGEDG1G2',
//   'E': 'AFEDG1G2',
//   'F': 'AFEG1G2',
//   'G': 'ABCFEDG2',
//   'H': 'BCGEG1G2',
//   'I': 'BG',
//   'J': 'CDEG1G2',
//   'K': 'HJEG1G2',
//   'L': 'FEDG1G2',
//   'M': 'ACGIEJG1G2',
//   'N': 'ACGEJHKG1G2',
//   'O': 'ABCEDG1G2',
//   'P': 'ABCEFG1G2',
//   'Q': 'ABCEDFG2K',
//   'R': 'ABCEFG1G2K',
//   'S': 'AFBGEDG2',
//   'T': 'AIK',
//   'U': 'BCDEFG2',
//   'V': 'EFIG1J',
//   'W': 'BDFHJMEG1G2',
//   'X': 'HIJKLMN',
//   'Y': 'HIKM',
//   'Z': 'ADG1G2KM'
// }


export const OpenAI14SegmentStarburst=

{
  ' ': '',
  '0': 'ABCDEF',
  '1': 'BC',
  '2': 'ABG1ED',
  '3': 'ABG1CD',
  '4': 'FG1BC',
  '5': 'AFG1CD',
  '6': 'AFEDCG1',
  '7': 'ABC',
  '8': 'ABCDEFVG1',
  '9': 'ABCDFG1',
  'A': 'ABCDEFHG1G2KN',
  'B': 'CDEFHG1G2K',
  'C': 'ADEFHG2',
  'D': 'BCDEG1G2K',
  'E': 'ADEFG1G2K',
  'F': 'AEFG1G2KH',
  'G': 'ACDEFG2K',
  'H': 'BCEFG1G2KHN',
  'I': 'BCJ',
  'J': 'DEFG2',
  'K': 'EFG1HKN',
  'L': 'DEFG2',
  'M': 'ACEG1IKM',
  'N': 'ABCEG1HKMN',
  'O': 'ABCDEFVG1G2',
  'P': 'ABEFG1G2H',
  'Q': 'ABCDEFG1G2K',
  'R': 'ABEFG1KH',
  'S': 'ACDFG2K',
  'T': 'AJK',
  'U': 'BCDEFG2K',
  'V': 'ADEG1N',
  'W': 'ADEG1KN',
  'X': 'BDEG1K',
  'Y': 'BDEG1KN',
  'Z': 'ACDEG1HKN'
}

export class Font14SegmentOpenAI {
  static encode4Digit(digit: string) {
    return FontUtil.digits4FromSegmentMap(OpenAI14SegmentStarburst, digit)
  }
}
